<a href="https://colab.research.google.com/github/WistonTravieso/Rds-data-optimization/blob/main/Visualizaci%C3%B3n_de_archivos_dbf_RDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Paso 1: Añadir la carpeta compartida a tu Google Drive

**Importante**: Antes de continuar, ve al enlace de Google Drive que proporcionaste (https://drive.google.com/drive/folders/1CieUv7Ea01jHUdp0zvYNbwJf8DqDJ2Z6?usp=drive_link) y añade la carpeta compartida 'Datos Memory' a tu 'Mi Unidad' (My Drive). Puedes hacerlo haciendo clic derecho en el nombre de la carpeta y seleccionando 'Añadir acceso directo a Drive' o 'Añadir a Mi unidad'. Esto permitirá que Colab la vea.

Una vez añadida, podrás encontrarla bajo una ruta similar a `/content/drive/My Drive/Riegos del sur/Datos Memory/`.

### Paso 2: Listar los archivos dentro de la carpeta compartida

Después de añadir la carpeta a tu 'Mi Unidad' y asegurarte de que tu Google Drive está montado (lo cual ya está hecho), puedes listar el contenido de la nueva carpeta. Asegúrate de ajustar la ruta si el nombre de la carpeta es diferente o si la colocaste en otra subcarpeta.

In [ ]:
# Ajusta esta ruta si la carpeta 'Datos Memory' tiene un nombre diferente o está dentro de otra carpeta en tu 'Mi Unidad'
!ls '/content/drive/My Drive/Riegos del sur/Datos Memory'

ARCLASIF.DBF   CCFONDOS.DBF  CLCLASIF.DBF  CPMOVCTA.DBF  PCDATOS.DBF
ARCOMPON.DBF   CCIMP.DBF     CLDATOS.DBF   CPREFS.DBF	 PGDATOS.DBF
ARDATOS.DBF    CCLINEAS.DBF  CLDATOS.FPT   CPVENC.DBF	 PGVENC.DBF
ARDATOS.FPT    CCMOVCTA.DBF  CLFONDOS.DBF  CSDATOS.DBF	 PRCLASIF.DBF
ARLOTES.DBF    CCREFS.DBF    CLMONEDA.DBF  CUDATOS.DBF	 PRDATOS.DBF
ARPRECIO.DBF   CCVENC.DBF    CODATOS.DBF   DODATOS.DBF	 PRDATOS.FPT
ARSER1.DBF     CFDATOS.DBF   CODATOS.FPT   DOVIAS.DBF	 PRFONDOS.DBF
ARSER2.DBF     CFFONDOS.DBF  COEMIS.DBF    FADATOS.DBF	 PRMONEDA.DBF
ARSTKMIN.DBF   CFMOVCTA.DBF  COVIAS.DBF    IMCOMPR.DBF	 SUCPROV.DBF
ARVALSER1.DBF  CKCAMPOS.DBF  CPCAMPOS.DBF  IMDATOS.DBF	 SUCURSAL.DBF
ARVALSER2.DBF  CKCTAS.DBF    CPCTAS.DBF    IMREGLA.DBF	 TADATOS.DBF
BADATOS.DBF    CKDATOS.DBF   CPDATOS.DBF   IVDATOS.DBF	 TRDATOS.DBF
CCCAMPOS.DBF   CKIMP.DBF     CPFONDOS.DBF  IVTASAS.DBF	 VCDATOS.DBF
CCDATOS.DBF    CKLINEAS.DBF  CPIMP.DBF	   MODATOS.DBF	 VEDATOS.DBF
CCDCTAS.DBF    CKMOVCTA.DBF  CPLINEAS.DBF  NUDATOS.DBF

### Paso 3: Instalar la librería `dbfread`

Ahora instalaremos la librería necesaria para leer archivos `.dbf`.

In [ ]:
!pip install dbfread

Collecting dbfread
  Downloading dbfread-2.0.7-py2.py3-none-any.whl.metadata (3.3 kB)
Downloading dbfread-2.0.7-py2.py3-none-any.whl (20 kB)
Installing collected packages: dbfread
Successfully installed dbfread-2.0.7

### Paso 4: Previsualizar cada archivo `.dbf`

Ahora vamos a recorrer todos los archivos `.dbf` encontrados en la carpeta y mostraremos las primeras filas de cada uno utilizando `dbfread` y `pandas`.

In [ ]:
import pandas as pd
from dbfread import DBF
import os

# Define la ruta de la carpeta donde están los archivos DBF
folder_path = '/content/drive/My Drive/Riegos del sur/Datos Memory'

# Lista todos los archivos .dbf en la carpeta
dbf_files = [f for f in os.listdir(folder_path) if f.endswith('.DBF') or f.endswith('.dbf')]

if not dbf_files:
    print(f"No se encontraron archivos DBF en la carpeta: {folder_path}")
else:
    print(f"Se encontraron {len(dbf_files)} archivos DBF. Previsualizando cada uno:")
    for dbf_file_name in dbf_files:
        dbf_file_path = os.path.join(folder_path, dbf_file_name)
        try:
            # Leer el archivo DBF
            # Se usa encoding='latin-1' o 'cp850' que son comunes para archivos DBF
            table = DBF(dbf_file_path, encoding='latin-1')
            df_dbf = pd.DataFrame(iter(table))

            print(f"\n--- Previsualización de '{dbf_file_name}' ---")
            display(df_dbf.head())
            print(f"Número de filas: {len(df_dbf)}")
            print(f"Columnas y tipos de datos:\n{df_dbf.info(verbose=False, memory_usage='deep')}")

        except Exception as e:
            print(f"Ocurrió un error al cargar '{dbf_file_name}': {e}")

Se encontraron 70 archivos DBF. Previsualizando cada uno:

--- Previsualización de 'VEDATOS.DBF' ---

  VENDEDOR            NOMBRE
0        1  Federico Delgado
1        2     Bruno Morales
2        3      Maria Romero
3        4                 A
4        5  Valeria Baptista

Número de filas: 8
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Columns: 2 entries, VENDEDOR to NOMBRE
dtypes: object(2)
memory usage: 1.0 KB
Columnas y tipos de datos:
None

--- Previsualización de 'CUDATOS.DBF' ---

   CUENTA                 NOMBRE MONEDA  TIPO
0       1                 ACTIVO      0     0
1     111       DISPONIBILIDADES      0     0
2    1111                   CAJA      0     0
3  111111    Caja Casa Central $      0     1
4  111112  Caja Casa Central U$S      1     1

Número de filas: 423
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 423 entries, 0 to 422
Columns: 4 entries, CUENTA to TIPO
dtypes: int64(1), object(3)
memory usage: 74.6 KB
Columnas y tipos de datos:
None

--- Previsualización de 'CKLINEAS.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'CCMOVCTA.DBF' ---

,CODIGO,SERIE,NUMERO,LETRA,FONDO,TIPOC,SERIEFON,NUMEROFON,BANCO,CTABANCO,...,MONEDA,COTIZACION,MONTO,LEYENDA,LIBRO,RETENCION,IVA,CONCILIA,RUC,CUENTABA
0,2,A,1,,0,0,,0,,,...,1,0.0,0.00,CONTADO A 1,V,,2,False,,
1,2,ETE,2,,1,1,,0,,,...,1,0.0,1.22,CONTADO ETE 2,V,,,False,,
2,2,ETE,2,,0,0,,0,,,...,1,0.0,0.00,CONTADO ETE 2,V,,2,False,,
3,2,ETE,2,,1,1,,0,,,...,1,0.0,-1.22,CONTADO ETE 2,V,,,False,,
4,2,ETE,3,,0,0,,0,,,...,1,0.0,0.00,CONTADO ETE 3,V,,2,False,,

Número de filas: 2101
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2101 entries, 0 to 2100
Columns: 29 entries, CODIGO to CUENTABA
dtypes: bool(1), float64(2), int64(7), object(19)
memory usage: 2.0 MB
Columnas y tipos de datos:
None

--- Previsualización de 'PCDATOS.DBF' ---

  CODIGO           NOMBRE BASE  PORCENTAJE  UTILIDAD  IVAINCLUID
0      1  Precio de Lista             0.00     False        True
1      5      Costo Tigre    1      -50.00     False        True
2      6           Compra             0.00     False        True
3      2   Costo New Drip    1      -37.00     False        True
4      3      Costo Hidro    1      -38.25     False        True

Número de filas: 11
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Columns: 6 entries, CODIGO to IVAINCLUID
dtypes: bool(2), float64(1), object(3)
memory usage: 2.0 KB
Columnas y tipos de datos:
None

--- Previsualización de 'CODATOS.DBF' ---

,CODIGO,NOMBRE,ABREVIADO,HABILITADO,BASICO,LETRA,EXENTO,PRECIO,COLOR,RECOBRANZA,...,DEDESTINO,TESORIGEN,ESTORIGEN,TESDESTINO,ESTDESTINO,ARTPENDIEN,EXPIMP,FACTURABOL,NOMVIAS,LINEAS
0,1,Factura de Venta Crédito,FACTURA,True,3,,False,2,32768,False,...,,1,1,0,,1,True,0,MX_CO_VIAS  A                   c   X_CO_VIA...,0
1,12,Cancelación de Pedido,CAN.PEDIDO,False,29,,False,2,8388736,False,...,1,1,2,1,1,1,False,0,MX_CO_VIAS  A                   c   X_CO_VIA...,0
2,11,Pedido de Clientes,PEDIDO,False,22,,False,2,8388736,False,...,1,1,1,1,2,1,False,0,MX_CO_VIAS  A                   c   X_CO_VIA...,0
3,5,Recibo de Cobranza,RECIBO,True,5,,False,1,8421440,False,...,1,2,1,2,1,0,False,0,MX_CO_VIAS  A                   c   X_CO_VIA...,0
4,21,Factura de Compra Crédito,FACTURA C.,True,1,,False,2,0,False,...,1,0,,1,1,1,False,0,MX_CO_VIAS  A                   c   X_CO_VIA...,0

Número de filas: 53
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Columns: 29 entries, CODIGO to LINEAS
dtypes: bool(6), int64(15), object(8)
memory usage: 190.7 KB
Columnas y tipos de datos:
None

--- Previsualización de 'TADATOS.DBF' ---

,CODIGO,NOMBRE,ABREVIADO,PRESENTA,TELEFONO1,TELEFONO2,CONTACTO,CODIGOMON0,CODIGOMON1,CUENTA,TIPOCUENTA
0,6,Plata Card,PLATA,,,,,,,6,1
1,7,Oca Card,OCA,,,,,,,7,1
2,9,Red Maestro,MAESTRO,,,,,,,9,1
3,4,American Express,AMERICAN,,,,,,,4,1
4,3,Diners,DINERS,,,,,,,3,1

Número de filas: 9
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Columns: 11 entries, CODIGO to TIPOCUENTA
dtypes: int64(1), object(10)
memory usage: 4.7 KB
Columnas y tipos de datos:
None

--- Previsualización de 'IMDATOS.DBF' ---

,CODIGO,NOMBRE,ABREVIADO,REGIMEN,COMPROB,GRAVADO,CODIGOIVA,DESDEFECHA,HASTAFECHA,TCUENTAVTA,TCUENTACOM,CUENTAVTA,CUENTACPRA,FORMACALC,PORCENTAJE,CODPRECIO,VALOR,CODSRI
0,COFIS,COFIS,COFIS,,2,True,,2001-06-01,2007-06-30,1,1,11341,2134,1,3.0,,0.0,0

Número de filas: 1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Columns: 18 entries, CODIGO to CODSRI
dtypes: bool(1), float64(2), int64(5), object(10)
memory usage: 685.0 bytes
Columnas y tipos de datos:
None

--- Previsualización de 'CLFONDOS.DBF' ---

      CLIENTE  TIPO
0           1     1
1           1     2
2           1     4
3           1     5
4           1     7

Número de filas: 17067
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17067 entries, 0 to 17066
Columns: 2 entries, CLIENTE to TIPO
dtypes: int64(1), object(1)
memory usage: 1.1 MB
Columnas y tipos de datos:
None

--- Previsualización de 'IMCOMPR.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'CPCTAS.DBF' ---

,CODIGO,SERIE,NUMERO,LETRA,PROVEEDOR,CUENTA,MONEDA,COTIZACION,MONTOCTA,CENTRO
0,21,A,26039,,12,210102001,1,0.0,2770.00,
1,21,A,166323,,3,210101001,1,0.0,2494.37,
2,21,A,165213,,3,110501001,1,0.0,398.07,
3,21,A,165357,,3,110501001,1,0.0,1084.50,
4,27,A,1,,1,113311,0,0.0,3000.00,

Número de filas: 5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Columns: 10 entries, CODIGO to CENTRO
dtypes: float64(2), int64(2), object(6)
memory usage: 1.8 KB
Columnas y tipos de datos:
None

--- Previsualización de 'CFDATOS.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'CFMOVCTA.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'CLCLASIF.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'CLDATOS.DBF' ---

,CLIENTE,NOMBRE,RSOCIAL,RUCRUTCUIT,DOCUMENTO,SITUIVA,GANANCIAS,DIRECCION,LOCALIDAD,CPOSTAL,...,NUM1,NUM2,NUM3,MEMO1,MEMO2,MEMO3,FECHA1,FECHA2,FECHA3,TRANSPORT
0,1,CONSUMIDOR FINAL,CONSUMIDOR FINAL,,,1,,,,,...,0.0,0.0,0.0,None,None,None,None,None,None,
1,1278,DALENE S.A,DALENE S.A,212073920017,,1,,,CIUDAD DE LA COSTA,,...,0.0,0.0,0.0,None,None,None,2016-12-19,2016-12-19,2016-12-19,
2,2,LAGARDE GRACIELA,LAGARDE GRACIELA,170073650010,,3,,RUTA 1 KM 47,San José,80100,...,0.0,0.0,0.0,None,None,None,2016-12-19,2016-12-19,2016-12-19,
3,1092,SOSA LUIS ANDRES,SOSA LUIS ANDRES,180111320016,,1,,RUTA 96 KM 24,DOLORES,,...,0.0,0.0,0.0,None,None,None,None,None,None,
4,4,BERTO IGNACIO,BERTO IGNACIO,170129000016,,3,,,,80100,...,0.0,0.0,0.0,None,None,None,2016-12-19,2016-12-19,2016-12-19,

Número de filas: 2556
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2556 entries, 0 to 2555
Columns: 48 entries, CLIENTE to TRANSPORT
dtypes: bool(1), float64(7), int64(3), object(37)
memory usage: 4.5 MB
Columnas y tipos de datos:
None

--- Previsualización de 'CKDATOS.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'MODATOS.DBF' ---

,CODIGO,NOMBRE,SIMBOLO,REDVENTAS,REDCALVTA,REDCOMPRAS,REDCALCOM,REDTOPECOM,REDPRECIOS,CUENTA,TIPOCUENTA,EFECTIVO,VUELTO
0,0,Pesos Uruguayos,$,2,2,2,2,10.0,2,410202097,2,1,0
1,1,Dólares,U$S,2,2,2,2,10.0,2,410202097,2,1,0

Número de filas: 2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Columns: 13 entries, CODIGO to VUELTO
dtypes: float64(1), int64(8), object(4)
memory usage: 739.0 bytes
Columnas y tipos de datos:
None

--- Previsualización de 'PGVENC.DBF' ---

  CODIGO  MESES  DIAS  IMPORTE
0      1      0     0    100.0
1      2      1     0    100.0
2      3      2     0    100.0
3      4      1     0     50.0
4      4      2     0     50.0

Número de filas: 7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Columns: 4 entries, CODIGO to IMPORTE
dtypes: float64(1), int64(2), object(1)
memory usage: 657.0 bytes
Columnas y tipos de datos:
None

--- Previsualización de 'CPFONDOS.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'COVIAS.DBF' ---

   CODIGO  NUMERO NOMBRE
0       5       1
1       3       1
2       4       1
3      13       1
4      13       2

Número de filas: 13
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Columns: 3 entries, CODIGO to NOMBRE
dtypes: int64(2), object(1)
memory usage: 977.0 bytes
Columnas y tipos de datos:
None

--- Previsualización de 'CKCAMPOS.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'IVTASAS.DBF' ---

,CODIGO,FECHA,TASA,TCUENTAVTA,TCUENTACOM,CUENTAVTA,CUENTACOM,CODIGOSRI,CODIGOAFIP,TESPECIAL,TADICIONAL
0,0,1900-01-01,0.0,,,0,0,0,0,0.0,0.0
1,1,2007-07-01,10.0,210301001,110302004,2,2,0,0,0.0,0.0
2,2,2007-07-01,22.0,210301001,110302003,2,2,0,0,0.0,0.0
3,1,2007-07-01,10.0,21332,113312,2,2,0,0,0.0,0.0
4,2,2007-07-01,22.0,21333,113313,2,2,0,0,0.0,0.0

Número de filas: 7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Columns: 11 entries, CODIGO to TADICIONAL
dtypes: float64(3), int64(4), object(4)
memory usage: 1.9 KB
Columnas y tipos de datos:
None

--- Previsualización de 'CPLINEAS.DBF' ---

,CODIGO,SERIE,NUMERO,LETRA,PROVEEDOR,LINEA,ARTICULO,ARTNOMBRE,CANTIDAD,CANTIDAD2,...,PIVAINC,IVA1DTO,IVA2DTO,IVA3DTO,CODIGOLOTE,ARSERIE,S1CODIGO,V1CODIGO,S2CODIGO,V2CODIGO
0,21,A,26039,,12,1,PV0016,TANQUE BICAPA 10000 LTS,2.0,0.0,...,1689.70,0.0,0.0,0.0,,,,,,
1,21,A,6934,,125,1,9096,BEBEDERO REDONDO 500 HORMIGON,20.0,0.0,...,168.00,0.0,0.0,0.0,,,,,,
2,21,A,6934,,125,2,9012,GASTOS DE FLETES,1.0,0.0,...,233.02,0.0,0.0,0.0,,,,,,
3,21,A,55229,,37,1,9015,MANTENIMIENTO DE EQUIPOS,1.0,0.0,...,2684.00,0.0,0.0,0.0,,,,,,
4,21,A,165236,,3,1,10060512,PE- TUBO PEAD 63MM PN 8,1700.0,0.0,...,2.04,0.0,0.0,0.0,,,,,,

Número de filas: 2315
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2315 entries, 0 to 2314
Columns: 45 entries, CODIGO to V2CODIGO
dtypes: float64(18), int64(7), object(20)
memory usage: 2.7 MB
Columnas y tipos de datos:
None

--- Previsualización de 'CCIMP.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'CPCAMPOS.DBF' ---

   CODIGO SERIE  NUMERO LETRA   PROVEEDOR CAMPO                  TEXTO
0      21     A  167553                 3     U  TUBCONEX URUGUAY S.A.
1      21     A  167553                 3     V
2      21     A  167553                 3     W           215409400018
3      22     A   39664                 1     W           217335280010
4      22     A   39664                 1     V

Número de filas: 318
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318 entries, 0 to 317
Columns: 7 entries, CODIGO to TEXTO
dtypes: int64(2), object(5)
memory usage: 89.1 KB
Columnas y tipos de datos:
None

--- Previsualización de 'CCLINEAS.DBF' ---

,CODIGO,SERIE,NUMERO,LETRA,LINEA,ARTICULO,ARTNOMBRE,CANTIDAD,CANTIDAD2,SIGNO,...,PIVAINC,IVA1DTO,IVA2DTO,IVA3DTO,CODIGOLOTE,ARSERIE,S1CODIGO,V1CODIGO,S2CODIGO,V2CODIGO
0,2,A,1,,1,001,ARTICULOS VARIOS,1.0,0.0,-1,...,0.00,0.0,0.0,0.0,,,,,,
1,2,ETE,2,,1,001,ARTICULOS VARIOS,1.0,0.0,-1,...,0.00,0.0,0.0,0.0,,,,,,
2,2,ETE,3,,1,001,ARTICULOS VARIOS,1.0,0.0,-1,...,0.00,0.0,0.0,0.0,,,,,,
3,1,EFA,24,,1,22503928,"SD-MANGUITO SD/BR DE 63 MM X 2""",12.0,0.0,-1,...,2.27,0.0,0.0,0.0,,,,,,
4,1,EFA,24,,2,22527177,SD-CUPLA 63 X 2,12.0,0.0,-1,...,3.09,0.0,0.0,0.0,,,,,,

Número de filas: 2463
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2463 entries, 0 to 2462
Columns: 43 entries, CODIGO to V2CODIGO
dtypes: float64(18), int64(7), object(18)
memory usage: 2.6 MB
Columnas y tipos de datos:
None

--- Previsualización de 'PGDATOS.DBF' ---

,CODIGO,NOMBRE,DESDE,TOTAL,CANTCUOTAS,SEPCMESES,SEPCDIAS,PRICMESES,PRICDIAS
0,1,Contado,F,100.0,1,0,0,0,0
1,2,30 Días,F,100.0,1,0,0,1,0
2,3,60 Días,F,100.0,1,0,0,2,0
3,4,30 y 60 Días,F,100.0,2,1,0,1,0
4,5,90 Días,F,100.0,1,0,0,3,0

Número de filas: 6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Columns: 9 entries, CODIGO to PRICDIAS
dtypes: float64(1), int64(5), object(3)
memory usage: 1.5 KB
Columnas y tipos de datos:
None

--- Previsualización de 'NUDATOS.DBF' ---

  CODIGO                NOMBRE SERIE  NUMERO
0      1        Ventas Crédito     A       1
1      2        Ventas Contado     A       2
2      3      Notas de Crédito     A       1
3      4  Devoluciones Contado     A       1
4      5               Pedidos     A       1

Número de filas: 5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Columns: 4 entries, CODIGO to NUMERO
dtypes: int64(1), object(3)
memory usage: 1.0 KB
Columnas y tipos de datos:
None

--- Previsualización de 'IMREGLA.DBF' ---

  CODIGO  NUMERO  CAMPO  TABLA  RELACION VALOR
0  COFIS       1      5      0         1     0
1  COFIS       2     13      3         1

Número de filas: 2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Columns: 6 entries, CODIGO to VALOR
dtypes: int64(4), object(2)
memory usage: 403.0 bytes
Columnas y tipos de datos:
None

--- Previsualización de 'CFFONDOS.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'DODATOS.DBF' ---

,CODIGO,NOMBRE,ABREVIADO,TIPO,EMISION,REPORTE,NUMERADOR,VIAS,TIPOCUENTA,CUENTA,CODCONCILI,CHEQUEDIA,TARJETA
0,1,Efectivo,EFECTIVO,1,0,,,0,0,1234567890,,False,0
1,3,Cheque recibido,CHEQUE,2,1,Generico,2,1,0,,,False,0
2,6,Cheque emitido,CHEQUE,3,0,,,0,0,,,False,0
3,2,Voucher de tarjeta de crédito,VOUCHER,4,0,,,0,0,,,False,0
4,5,Conforme recibido,CONFORME,7,0,,,0,0,,,False,0

Número de filas: 9
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Columns: 13 entries, CODIGO to TARJETA
dtypes: bool(1), int64(6), object(6)
memory usage: 3.4 KB
Columnas y tipos de datos:
None

--- Previsualización de 'CCFONDOS.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'CPMOVCTA.DBF' ---

,CODIGO,SERIE,NUMERO,LETRA,PROVEEDOR,FONDO,TIPOC,SERIEFON,NUMEROFON,BANCO,...,MONEDA,COTIZACION,MONTO,LEYENDA,LIBRO,IVA,CONCILIA,RETENCION,RUC,CUENTABA
0,21,A,26039,,12,0,0,,0,,...,1,0.0,2770.00,FACTURA C. A 26039,C,,False,,,
1,21,A,26039,,12,0,0,,0,,...,1,0.0,3379.40,FACTURA C. A 26039,C,2,False,,,
2,21,A,26039,,12,0,0,,0,,...,1,0.0,0.00,FACTURA C. A 26039,C,2,False,,,
3,21,A,6934,,125,0,0,,0,,...,1,0.0,3257.02,FACTURA C. A 6934,C,,False,,,
4,21,A,6934,,125,0,0,,0,,...,1,0.0,0.00,FACTURA C. A 6934,C,,False,,,

Número de filas: 2460
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2460 entries, 0 to 2459
Columns: 30 entries, CODIGO to CUENTABA
dtypes: bool(1), float64(2), int64(7), object(20)
memory usage: 2.5 MB
Columnas y tipos de datos:
None

--- Previsualización de 'COEMIS.DBF' ---

,PC,CODIGO,LETRA,NUMERADOR,EMISION,REPORTE,LINEAS,FORMULARIO,TINCREMENT,INCREMENTO
0,*,1,,,1,Generico,0,,,0
1,*,2,,,1,Generico,0,,,0
2,*,3,,,1,Generico,0,,,0
3,*,4,,,1,Generico,0,,,0
4,*,5,,,1,recibo,0,,,0

Número de filas: 56
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Columns: 10 entries, PC to INCREMENTO
dtypes: int64(4), object(6)
memory usage: 18.1 KB
Columnas y tipos de datos:
None

--- Previsualización de 'CCVENC.DBF' ---

   CODIGO SERIE  NUMERO LETRA       VENCE  MONTOVEN
0       1   EFA      24        2025-10-25   1313.23
1       1   EFA       2        2025-10-22   1510.34
2       1   EFA       3        2025-10-22    153.72
3       1   EFA      18        2025-10-22    409.92
4       1   EFA      14        2025-10-22     76.86

Número de filas: 422
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 422 entries, 0 to 421
Columns: 6 entries, CODIGO to MONTOVEN
dtypes: float64(1), int64(2), object(3)
memory usage: 68.1 KB
Columnas y tipos de datos:
None

--- Previsualización de 'CKMOVCTA.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'CCDCTAS.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'CKIMP.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'TRDATOS.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'CPVENC.DBF' ---

   CODIGO SERIE  NUMERO LETRA   PROVEEDOR       VENCE  MONTOVEN
0      21     A   26039                12  2025-09-25   3379.40
1      21     A    6934               125  2025-11-29   1628.51
2      21     A    6934               125  2025-10-29   1628.51
3      21     A   55229                37  2025-12-21   2684.00
4      21     A  165236                 3  2025-12-29   3463.58

Número de filas: 392
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392 entries, 0 to 391
Columns: 7 entries, CODIGO to MONTOVEN
dtypes: float64(1), int64(2), object(4)
memory usage: 85.1 KB
Columnas y tipos de datos:
None

--- Previsualización de 'DOVIAS.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'CLMONEDA.DBF' ---

      CLIENTE MONEDA
0           1      0
1           1      1
2        1278      0
3        1278      1
4           2      0

Número de filas: 5111
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5111 entries, 0 to 5110
Columns: 2 entries, CLIENTE to MONEDA
dtypes: object(2)
memory usage: 544.2 KB
Columnas y tipos de datos:
None

--- Previsualización de 'CCREFS.DBF' ---

,CODIGO,SERIE,NUMERO,LETRA,MONTO,CODIGOREF,SERIEREF,NUMEROREF,LETRAREF,MONTOREF,MANUAL
0,1,EFA,1,,1400.56,3,NCF,2,,1400.56,True
1,1,EFA,2,,1510.34,5,REFA,29,,1510.34,True
2,1,EFA,3,,153.72,5,REFA,29,,153.72,True
3,1,EFA,4,,3629.50,3,NCF,1,,3629.50,True
4,1,EFA,5,,255.00,5,REFA,27,,255.00,True

Número de filas: 356
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356 entries, 0 to 355
Columns: 11 entries, CODIGO to MANUAL
dtypes: bool(1), float64(2), int64(4), object(4)
memory usage: 87.7 KB
Columnas y tipos de datos:
None

--- Previsualización de 'IVDATOS.DBF' ---

  CODIGO                NOMBRE   CUENTAVTA   CUENTACOM  TCUENTAVTA  TCUENTACOM
0      0            IVA Exento           0           0           0           0
1      1       IVA Tasa Mínima           0           0           0           0
2      2       IVA Tasa Básica           0           0           0           0
3      3  IVA Gastos T. Básica           0           0           0           0
4      4            IVA Gasoil           0           0           0           0

Número de filas: 5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Columns: 6 entries, CODIGO to TCUENTACOM
dtypes: int64(2), object(4)
memory usage: 1.4 KB
Columnas y tipos de datos:
None

--- Previsualización de 'CPDATOS.DBF' ---

,CODIGO,TIPOB,SERIE,NUMERO,PROVEEDOR,FECHA,SITUIVA,CONDPAGO,MONEDACTA,MONEDA,...,PRECIO,IVACODIGO,CODIGOSRI,CA_FEC_CAD,SUCPRO,IDCABREF,ESDESTINO,DEDESTINO,ESORIGEN,DEORIGEN
0,21,1,A,26039,12,2025-09-25,,1,1,1,...,,2,0,None,,,1,1,,
1,21,1,A,6934,125,2025-09-29,,4,1,1,...,,,0,None,,,1,1,,
2,21,1,A,55229,37,2025-10-21,,3,1,1,...,,2,0,None,,,1,1,,
3,21,1,A,165236,3,2025-09-29,,5,1,1,...,1,2,0,None,,,1,1,,
4,21,1,A,165292,3,2025-09-30,,5,1,1,...,1,2,0,None,,,1,1,,

Número de filas: 719
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 719 entries, 0 to 718
Columns: 40 entries, CODIGO to DEORIGEN
dtypes: bool(1), float64(14), int64(6), object(19)
memory usage: 759.4 KB
Columnas y tipos de datos:
None

--- Previsualización de 'BADATOS.DBF' ---

  CODIGO                NOMBRE  ABREVIADO CUENTA  TIPOCUENTA
0    001                  BROU       BROU                  0
1    104            Banco ACAC       ACAC                  0
2    101  Banco La Caja Obrera     OBRERA                  0
3    102       Banco Comercial  COMERCIAL                  0
4    103      Banco de Crédito    CREDITO                  0

Número de filas: 23
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Columns: 5 entries, CODIGO to TIPOCUENTA
dtypes: int64(1), object(4)
memory usage: 5.3 KB
Columnas y tipos de datos:
None

--- Previsualización de 'CPIMP.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'CCCAMPOS.DBF' ---

   CODIGO SERIE  NUMERO LETRA CAMPO                                TEXTO
0       2   EFA     505           W                         170210900013
1       2   EFA     505           V  RUTA 1 KM 46.300 CHACRA  "LA CAMELI
2       2   EFA     505           U                    MACKINNON GABRIEL
3       2   EFA     597           W                         150970970016
4       2   EFA     597           V

Número de filas: 9
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Columns: 6 entries, CODIGO to TEXTO
dtypes: int64(2), object(4)
memory usage: 2.2 KB
Columnas y tipos de datos:
None

--- Previsualización de 'CKCTAS.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'CCDATOS.DBF' ---

,CODIGO,TIPOB,SERIE,NUMERO,FECHA,CLIENTE,SITUIVA,VENDEDOR,CONDPAGO,PRECIO,...,EXPVER,EXPTRA,EXPEMB,EXPFUE,EXPFOB,EXPCOM,ESDESTINO,DEDESTINO,ESORIGEN,DEORIGEN
0,2,10,A,1,2025-10-15,1,,1,1,1,...,0,,None,,0.0,0.0,,,1,1
1,2,10,ETE,2,2025-10-15,1,,1,1,1,...,0,,None,,0.0,0.0,,,1,1
2,2,10,ETE,3,2025-10-15,1,,1,1,1,...,0,,None,,0.0,0.0,,,1,1
3,1,3,EFA,24,2025-10-25,3120,,1,1,1,...,0,,None,,0.0,0.0,,,1,1
4,5,5,REFA,29,2025-10-25,3120,,,,,...,0,,None,,0.0,0.0,,,,

Número de filas: 775
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 775 entries, 0 to 774
Columns: 47 entries, CODIGO to DEORIGEN
dtypes: float64(16), int64(7), object(24)
memory usage: 1007.2 KB
Columnas y tipos de datos:
None

--- Previsualización de 'SUCURSAL.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'CPREFS.DBF' ---

,CODIGO,SERIE,NUMERO,LETRA,PROVEEDOR,MONTO,CODIGOREF,SERIEREF,NUMEROREF,LETRAREF,PROVEEDREF,MONTOREF,MANUAL
0,21,A,510,,98,24613.5,25,A,510,,98,24613.5,True
1,21,A,512,,98,1331.7,25,A,34,,98,1331.7,True
2,21,A,512,,98,20000.0,25,A,33,,98,20000.0,True
3,21,A,513,,98,13000.0,25,P,22042026,,98,13000.0,True
4,21,A,651,,27,47376.0,25,A,139,,27,47376.0,True

Número de filas: 331
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 331 entries, 0 to 330
Columns: 13 entries, CODIGO to MANUAL
dtypes: bool(1), float64(2), int64(4), object(6)
memory usage: 118.1 KB
Columnas y tipos de datos:
None

--- Previsualización de 'ARCLASIF.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'ARCOMPON.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'ARLOTES.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'ARSER2.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'ARPRECIO.DBF' ---

  LISTA  ARTICULO PRECIO MONEDA    UNITARIO    VIGENCIA  IVAINCLUID
0     1   HD1000B      1      1   13.114754  2017-01-03        16.0
1     1   AC-5150      1      1   39.344262  2017-01-03        48.0
2     1   FDO150F      1      1  323.770492  2017-01-04       395.0
3     1  AC-8080C      1      1   34.426230  2017-01-04        42.0
4     1  AC-8070C      1      1   31.147541  2017-01-04        38.0

Número de filas: 7859
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7859 entries, 0 to 7858
Columns: 7 entries, LISTA to IVAINCLUID
dtypes: float64(2), object(5)
memory usage: 2.0 MB
Columnas y tipos de datos:
None

--- Previsualización de 'ARSER1.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'ARVALSER2.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'VCDATOS.DBF' ---

  CLASE VALOR       NOMBRE
0  DEPT     1   Montevideo
1  DEPT     2      Artigas
2  DEPT     3    Canelones
3  DEPT     4  Cerro Largo
4  DEPT     5      Durazno

Número de filas: 107
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Columns: 3 entries, CLASE to NOMBRE
dtypes: object(3)
memory usage: 17.4 KB
Columnas y tipos de datos:
None

--- Previsualización de 'ARSTKMIN.DBF' ---

  ARTICULO DEPOSITO  STKMINIMO
0        1        1        0.0
1      001        1        0.0
2     2050        1        0.0
3     2051        1        0.0
4     2052        1        0.0

Número de filas: 4727
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4727 entries, 0 to 4726
Columns: 3 entries, ARTICULO to STKMINIMO
dtypes: float64(1), object(2)
memory usage: 537.7 KB
Columnas y tipos de datos:
None

--- Previsualización de 'CSDATOS.DBF' ---

,CLASE,NOMBRE,CLIENTES,PROVEEDS,ARTICULOS,GENERO,SINGULAR,MAYUSCULA
0,ZONA,CarpetaZonas,True,True,False,1,Zona,True
1,GIRO,CarpetaGiros,True,True,False,0,Giro,True
2,DEPT,CarpetaDepartamentos,True,True,False,0,Departamento,True

Número de filas: 3
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Columns: 8 entries, CLASE to MAYUSCULA
dtypes: bool(4), int64(1), object(3)
memory usage: 685.0 bytes
Columnas y tipos de datos:
None

--- Previsualización de 'FADATOS.DBF' ---

  FAMILIA               NOMBRE
0       1  ARTICULOS/SERVICIOS
1     001          GALVANIZADO
2     002               VARIOS
3     003          TERMOFUSION
4     004   MANGUERAS Y CONECC

Número de filas: 23
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Columns: 2 entries, FAMILIA to NOMBRE
dtypes: object(2)
memory usage: 2.7 KB
Columnas y tipos de datos:
None

--- Previsualización de 'ARVALSER1.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'ARDATOS.DBF' ---

,ARTICULO,NOMBRE,FAMILIA,DESCRIP,OBSERV,IVA,UNIDAD,EMPAQUE,UTILIDAD,STKMINIMO,...,FECHA1,FECHA2,FECHA3,CODCONV,CODCONP,CODCONC,TIPOART,FECHACOST,MONEDACOST,COSTO
0,1,Artículo o Servicio,1,,None,2,UNI,1.0,0.0,0.0,...,None,None,None,0,0,0,0,2026-04-29,0,0.00
1,001,ARTICULOS VARIOS,002,,None,2,UNI,1.0,0.0,0.0,...,None,None,None,2,0,2,0,2026-04-29,0,598.34
2,XKS-810PL,SUMERGIBLE ACHIQUE LEO 1 HP,020,,None,2,UNI,1.0,0.0,0.0,...,None,None,None,2,0,2,0,2026-04-29,0,1563.87
3,100032979,VT-TUBO 110X3.2 6M JEI UNIT4435 SN4,016,,None,2,UNI,1.0,40.0,0.0,...,None,None,None,2,0,2,0,2026-04-29,0,918.64
4,SS075M,ELECTROBOMBA 0.75 HP MONO EMAUX,021,,None,2,UNI,1.0,0.0,0.0,...,None,None,None,2,0,2,0,2026-04-29,0,12554.23

Número de filas: 4770
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4770 entries, 0 to 4769
Columns: 49 entries, ARTICULO to COSTO
dtypes: bool(6), float64(8), int64(7), object(28)
memory usage: 6.3 MB
Columnas y tipos de datos:
None

--- Previsualización de 'PRCLASIF.DBF' ---

Empty DataFrame
Columns: []
Index: []

Número de filas: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
Columnas y tipos de datos:
None

--- Previsualización de 'SUCPROV.DBF' ---

    PROVEEDOR SUCURSAL   NOMBRE       DIRECC      LOCALI    TELEF DEPTO
0           1        1  Suc Uno  DireSuc Uno  LocSuc Uno  1111111     1

Número de filas: 1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Columns: 7 entries, PROVEEDOR to DEPTO
dtypes: object(7)
memory usage: 522.0 bytes
Columnas y tipos de datos:
None

--- Previsualización de 'PRMONEDA.DBF' ---

    PROVEEDOR MONEDA
0           1      0
1           1      1
2           4      0
3           4      1
4           5      0

Número de filas: 367
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Columns: 2 entries, PROVEEDOR to MONEDA
dtypes: object(2)
memory usage: 39.2 KB
Columnas y tipos de datos:
None

--- Previsualización de 'PRDATOS.DBF' ---

,PROVEEDOR,NOMBRE,RSOCIAL,RUCRUTCUIT,SITUIVA,GANANCIAS,DIRECCION,LOCALIDAD,CPOSTAL,DEPTPROV,...,TEXTO3,NUM1,NUM2,NUM3,MEMO1,MEMO2,MEMO3,FECHA1,FECHA2,FECHA3
0,1,PROVEEDORES VARIOS,PROVEEDORES VARIOS,,1,,,,,1,...,,0.0,0.0,0.0,None,None,None,2016-12-19,2016-12-19,2016-12-19
1,4,BAKO S.A,BAKO S.A,210308300017,1,,GALICIA 1650,MONTEVIDEO,,1,...,,0.0,0.0,0.0,None,None,None,2016-12-19,2016-12-19,2016-12-19
2,5,HIDRO SERVICE SRL,HIDRO SERVICE SRL,211153370015,1,,SAN MARTIN 2868,MONTEVIDEO,,1,...,,0.0,0.0,0.0,None,None,None,2016-12-19,2016-12-19,2016-12-19
3,6,DREGHAL S.A.,DREGHAL S.A.,210030860016,1,,PARAGUAY 1616 BIS,,,1,...,,0.0,0.0,0.0,None,None,None,2016-12-19,2016-12-19,2016-12-19
4,8,NICOLL S.A,NICOLL S.A,215075820014,1,,DANUBIO 5122,MONTEVIDEO,,1,...,,0.0,0.0,0.0,None,None,None,2016-12-19,2016-12-19,2016-12-19

Número de filas: 184
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Columns: 45 entries, PROVEEDOR to FECHA3
dtypes: bool(2), float64(6), int64(3), object(34)
memory usage: 304.7 KB
Columnas y tipos de datos:
None

--- Previsualización de 'PRFONDOS.DBF' ---

    PROVEEDOR  TIPO
0           1     1
1           1     2
2           1     3
3           1     4
4           1     5

Número de filas: 2024
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2024 entries, 0 to 2023
Columns: 2 entries, PROVEEDOR to TIPO
dtypes: int64(1), object(1)
memory usage: 132.6 KB
Columnas y tipos de datos:
None

### Análisis del archivo `ARDATOS.DBF`

In [ ]:
# Especifica el nombre del archivo DBF a analizar
ardatos_file_name = 'ARDATOS.DBF'
ardatos_file_path = os.path.join(folder_path, ardatos_file_name)

try:
    # Cargar el archivo ARDATOS.DBF en un DataFrame de pandas
    print(f"Cargando el archivo: {ardatos_file_name}")
    table_ardatos = DBF(ardatos_file_path, encoding='latin-1')
    df_ardatos = pd.DataFrame(iter(table_ardatos))

    print(f"\n--- Primeras 5 filas de '{ardatos_file_name}' ---")
    display(df_ardatos.head())

    print(f"\n--- Información general de '{ardatos_file_name}' ---")
    df_ardatos.info(verbose=True, memory_usage='deep')

    print(f"\n--- Estadísticas descriptivas de '{ardatos_file_name}' ---")
    display(df_ardatos.describe(include='all'))

    print(f"\n--- Conteo de valores nulos por columna en '{ardatos_file_name}' ---")
    display(df_ardatos.isnull().sum().to_frame(name='valores_nulos'))

except Exception as e:
    print(f"Ocurrió un error al cargar o analizar '{ardatos_file_name}': {e}")

Cargando el archivo: ARDATOS.DBF

--- Primeras 5 filas de 'ARDATOS.DBF' ---

,ARTICULO,NOMBRE,FAMILIA,DESCRIP,OBSERV,IVA,UNIDAD,EMPAQUE,UTILIDAD,STKMINIMO,...,FECHA1,FECHA2,FECHA3,CODCONV,CODCONP,CODCONC,TIPOART,FECHACOST,MONEDACOST,COSTO
0,1,Artículo o Servicio,1,,None,2,UNI,1.0,0.0,0.0,...,None,None,None,0,0,0,0,2026-04-29,0,0.00
1,001,ARTICULOS VARIOS,002,,None,2,UNI,1.0,0.0,0.0,...,None,None,None,2,0,2,0,2026-04-29,0,598.34
2,XKS-810PL,SUMERGIBLE ACHIQUE LEO 1 HP,020,,None,2,UNI,1.0,0.0,0.0,...,None,None,None,2,0,2,0,2026-04-29,0,1563.87
3,100032979,VT-TUBO 110X3.2 6M JEI UNIT4435 SN4,016,,None,2,UNI,1.0,40.0,0.0,...,None,None,None,2,0,2,0,2026-04-29,0,918.64
4,SS075M,ELECTROBOMBA 0.75 HP MONO EMAUX,021,,None,2,UNI,1.0,0.0,0.0,...,None,None,None,2,0,2,0,2026-04-29,0,12554.23

--- Información general de 'ARDATOS.DBF' ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4770 entries, 0 to 4769
Data columns (total 49 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ARTICULO    4770 non-null   object
 1   NOMBRE      4770 non-null   object
 2   FAMILIA     4770 non-null   object
 3   DESCRIP     4770 non-null   object
 4   OBSERV      0 non-null      object
 5   IVA         4770 non-null   object
 6   UNIDAD      4770 non-null   object
 7   EMPAQUE     4770 non-null   float64
 8   UTILIDAD    4770 non-null   float64
 9   STKMINIMO   4770 non-null   float64
 10  PROVEEDOR   4770 non-null   object
 11  DEMORA      4770 non-null   int64
 12  CUENTAVTA   4770 non-null   object
 13  CUENTACPRA  4770 non-null   object
 14  CUENTAPROD  4770 non-null   object
 15  FOTO        0 non-null      object
 16  WEB         4770 non-null   bool
 17  CODBARRAS   4770 non-null   int64
 18  BARRAS      4770 non-null   object
 19  UNIDAD2     4770 non-null   object
 20  UNIDADREL   4770 non-null   float64
 21  NOTAS       4770 non-null   object
 22  COSTEA      4770 non-null   bool
 23  RELAC       4770 non-null   int64
 24  NROSERIE    4770 non-null   bool
 25  VENCIM      4770 non-null   bool
 26  LOTES       4770 non-null   bool
 27  USAATRIB    4770 non-null   bool
 28  PRIMERAT    4770 non-null   object
 29  SEGUNDOAT   4770 non-null   object
 30  TEXTO1      4770 non-null   object
 31  TEXTO2      4770 non-null   object
 32  TEXTO3      4770 non-null   object
 33  NUM1        4770 non-null   float64
 34  NUM2        4770 non-null   float64
 35  NUM3        4770 non-null   float64
 36  MEMO1       0 non-null      object
 37  MEMO2       0 non-null      object
 38  MEMO3       0 non-null      object
 39  FECHA1      1521 non-null   object
 40  FECHA2      1521 non-null   object
 41  FECHA3      1521 non-null   object
 42  CODCONV     4770 non-null   int64
 43  CODCONP     4770 non-null   int64
 44  CODCONC     4770 non-null   int64
 45  TIPOART     4770 non-null   int64
 46  FECHACOST   4758 non-null   object
 47  MONEDACOST  4770 non-null   object
 48  COSTO       4770 non-null   float64
dtypes: bool(6), float64(8), int64(7), object(28)
memory usage: 6.3 MB

--- Estadísticas descriptivas de 'ARDATOS.DBF' ---

,ARTICULO,NOMBRE,FAMILIA,DESCRIP,OBSERV,IVA,UNIDAD,EMPAQUE,UTILIDAD,STKMINIMO,...,FECHA1,FECHA2,FECHA3,CODCONV,CODCONP,CODCONC,TIPOART,FECHACOST,MONEDACOST,COSTO
count,4770,4770,4770,4770,0,4770,4770,4770.000000,4770.000000,4770.000000,...,1521,1521,1521,4770.000000,4770.000000,4770.000000,4770.000000,4758,4770,4770.00000
unique,4770,4691,23,14,0,5,2,NaN,NaN,NaN,...,1,1,1,NaN,NaN,NaN,NaN,1,1,NaN
top,AJM75S,"BOMBA HISER 4"" 3 HP TRIF.",002,,NaN,2,UNI,NaN,NaN,NaN,...,2016-12-19,2016-12-19,2016-12-19,NaN,NaN,NaN,NaN,2026-04-29,0,NaN
freq,1,4,1222,4750,NaN,4656,4768,NaN,NaN,NaN,...,1521,1521,1521,NaN,NaN,NaN,NaN,4758,4770,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.999790,0.616771,0.001048,...,NaN,NaN,NaN,1.982390,0.000419,1.994969,0.000629,NaN,NaN,324.59753
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.014479,3.963755,0.032363,...,NaN,NaN,NaN,0.186862,0.028958,0.100198,0.025073,NaN,NaN,6653.32934
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.00000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,...,NaN,NaN,NaN,2.000000,0.000000,2.000000,0.000000,NaN,NaN,0.00000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,...,NaN,NaN,NaN,2.000000,0.000000,2.000000,0.000000,NaN,NaN,0.00000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,0.000000,...,NaN,NaN,NaN,2.000000,0.000000,2.000000,0.000000,NaN,NaN,0.00000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,60.000000,1.000000,...,NaN,NaN,NaN,2.000000,2.000000,2.000000,1.000000,NaN,NaN,437288.39000

--- Conteo de valores nulos por columna en 'ARDATOS.DBF' ---

            valores_nulos
ARTICULO                0
NOMBRE                  0
FAMILIA                 0
DESCRIP                 0
OBSERV               4770
IVA                     0
UNIDAD                  0
EMPAQUE                 0
UTILIDAD                0
STKMINIMO               0
PROVEEDOR               0
DEMORA                  0
CUENTAVTA               0
CUENTACPRA              0
CUENTAPROD              0
FOTO                 4770
WEB                     0
CODBARRAS               0
BARRAS                  0
UNIDAD2                 0
UNIDADREL               0
NOTAS                   0
COSTEA                  0
RELAC                   0
NROSERIE                0
VENCIM                  0
LOTES                   0
USAATRIB                0
PRIMERAT                0
SEGUNDOAT               0
TEXTO1                  0
TEXTO2                  0
TEXTO3                  0
NUM1                    0
NUM2                    0
NUM3                    0
MEMO1                4770
MEMO2                4770
MEMO3                4770
FECHA1               3249
FECHA2               3249
FECHA3               3249
CODCONV                 0
CODCONP                 0
CODCONC                 0
TIPOART                 0
FECHACOST              12
MONEDACOST              0
COSTO                   0